FROM public.ecr.aws/lambda/python:3.12

# Copia dependencias y código fuente
COPY pyproject.toml ${LAMBDA_TASK_ROOT}/
COPY app/ ${LAMBDA_TASK_ROOT}/app/

# Instala dependencias (si usas poetry, pip, etc.)
RUN pip install .

# Define el handler: app/main.py -> handler
CMD ["app.main.handler"]