"""empty message

Revision ID: b99874171331
Revises: e41fc5779294
Create Date: 2025-09-04 13:39:02.901556

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = "b99874171331"
down_revision: Union[str, Sequence[str], None] = "e41fc5779294"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "app_user",
        "status",
        existing_type=postgresql.ENUM(
            "ACTIVE", "INACTIVE", "SUSPENDED", name="userstatus"
        ),
        nullable=True,
    )
    op.add_column(
        "organization",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "organization",
        sa.Column("logo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "organization",
        sa.Column("main_color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )

    user_type_table = sa.table(
        "user_type",
        sa.column("id", sa.String),
        sa.column("name", sa.String),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )

    op.bulk_insert(
        user_type_table,
        [
            {
                "name": "admin",
                "id": "3e1208bc-aa8d-42d7-b957-95895a2f60aa",
                "created_at": datetime(2025, 9, 4, 13, 45, 58),
                "updated_at": datetime(2025, 9, 4, 13, 46, 1),
            }
        ],
    )

    document_type_table = sa.table(
        "document_type",
        sa.column("id", sa.String),
        sa.column("name", sa.String),
        sa.column("abreviation", sa.String),
        sa.column("country_id", sa.String),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )

    op.bulk_insert(
        document_type_table,
        [
            {
                "id": "14580359-65d1-4f29-bd47-21c8d1b8f9bb",
                "created_at": datetime(2025, 9, 4, 13, 48, 6),
                "updated_at": datetime(2025, 9, 4, 13, 48, 10),
                "name": "Cédula de ciudadania",
                "abreviation": "CC",
                "country_id": "657dd949-8a95-4c29-9194-c2d85877f6ac",
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "main_color")
    op.drop_column("organization", "logo")
    op.drop_column("organization", "name")
    op.alter_column(
        "app_user",
        "status",
        existing_type=postgresql.ENUM(
            "ACTIVE", "INACTIVE", "SUSPENDED", name="userstatus"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
