"""empty message

Revision ID: c90f2fa956f9
Revises:
Create Date: 2025-09-04 11:04:09.031222

"""

import json
import os
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c90f2fa956f9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    countries_table = op.create_table(
        "country",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("iso", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "nice_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("iso3", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
        sa.Column("num_code", sa.Integer(), nullable=True),
        sa.Column("phone_code", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iso"),
        sa.UniqueConstraint("iso3"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("nice_name"),
    )
    op.create_table(
        "document_type",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column(
            "abreviation", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False
        ),
        sa.Column("country", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country"],
            ["country.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "app_user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("document_type_id", sa.Uuid(), nullable=False),
        sa.Column(
            "document_number",
            sqlmodel.sql.sqltypes.AutoString(length=40),
            nullable=False,
        ),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    data_file = os.path.join(os.path.dirname(__file__), "data", "countries.json")
    with open(data_file, "r", encoding="utf-8") as f:
        countries_data = json.load(f)

    op.bulk_insert(countries_table, countries_data)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_user")
    op.drop_table("document_type")
    op.drop_table("country")
    # ### end Alembic commands ###
