[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.36",
    "psycopg2-binary>=2.9.10",
    "sqlmodel>=0.0.25",
]
