name: Build & Test FastAPI Image

on:
  push:
    branches: [ "dev" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t fastapi-app:test .

      - name: Run container test (check health)
        run: |
          docker run -d --rm -p 8000:8000 --name fastapi-test fastapi-app:test
          sleep 10
          curl --fail http://127.0.0.1:8000/docs
          docker stop fastapi-test
